name: Terraform Apply

on:
  pull_request_review:
    types:
      - submitted

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: tfplan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Apply
        run: terraform apply tfplan
